### ISSUE TITLE
Update the ISO to docker v1.13.1

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift-b2d-iso#28]
At this point we are running relatively old version of docker i.e. 1.12.3 and we should update it latest docker i.e. https://github.com/boot2docker/boot2docker/releases/tag/v1.13.1

**Comment by brgnepal** [comment]
I am kind of bit thinking here about how often we should do it?
- Update docker version as soon as after upstream boot2docker release
- Based on some interval like 2/3 releases
- Based on some major changes in the docker which seems stable 

What could be a better approach here?
Looking at docker release page, it seems they releases two version in around month time.
Since 1.12.6 (jan 11) they have  1.13.0 and 1.13.1 till now. Refer https://github.com/docker/docker/tags.

cc @LalatenduMohanty @hferentschik

**Comment by praveenkumar** [comment]
I think we should have docker version consistent across the iso (cantos/rhel/b2d) because when something start failing we elminate different docker version might be issue.

**Comment by gbraad** [comment]
The problem here is that RHEL/CentOS Docker is not necessarily the same as the released Docker CE version. They should mostly be on par when it comes to functionality, but behaviour might still differ for certain features; such as volume mounts, etc.

**Comment by gbraad** [comment]
Why do we allow to select the version of Docker to be installed? https://github.com/gbraad/minishift-b2d-iso/issues/1 To me this sounds like an unnecessary burden towards testing effort.
