### ISSUE TITLE
Enable NFS installation test

### ISSUE THREAD

**Issue by brgnepal** [minishift/minishift-b2d-iso#55]
Currently, test case to check NFS installation has been commented out due to issue https://github.com/minishift/minishift/issues/660 which is fixed now.

See https://github.com/minishift/minishift-b2d-iso/blob/master/tests/test.py#L69-L74

Also, found that `mount.nfs -V <anypath>` does return version. Might be bug in `mount.nfs`
```
docker@minishift:~$ sudo /sbin/mount.nfs -V 
usage: mount.nfs remotetarget dir [-rvVwfnsh] [-o nfsoptions]
options:
	-r		Mount file system readonly
	-v		Verbose
	-V		Print version
	-w		Mount file system read-write
	-f		Fake mount, do not actually mount
	-n		Do not update /etc/mtab
	-s		Tolerate sloppy mount options rather than fail
	-h		Print this help
	nfsoptions	Refer to mount.nfs(8) or nfs(5)

docker@minishift:~$ sudo /sbin/mount.nfs -V ''     # Empty string after -V
mount.nfs: (linux nfs-utils 1.3.3)

docker@minishift:~$ sudo /sbin/mount.nfs -V /
mount.nfs: (linux nfs-utils 1.3.3)
```

**Comment by gbraad** [comment]
The issue is within the mount.nfs command, and was noted on https://github.com/minishift/minishift-b2d-iso/pull/45#discussion_r128491424. I have tried to get an answer from the community and the maintainer of the package, but no response. If this works, I would make the path clearly a need to make it work, such as

`sudo /sbin/mount.nfs -V 'needed to get version'`
or
`sudo /sbin/mount.nfs -V /needed/to/get/version`

**Comment by brgnepal** [comment]
> sudo /sbin/mount.nfs -V /needed/to/get/version

:+1:
